import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { FiCheckCircle, FiShield, FiClock, FiActivity, FiChevronRight } from 'react-icons/fi'
import { DISEASE_DATABASE } from '../data/diseaseData'
import { useTranslation } from 'react-i18next'

export default function AdvisoryPanel() {
  const { t, i18n } = useTranslation()
  
  // Only show actual diseases, maybe skip exact duplicates if necessary, but we'll list the main ones.
  const diseases = Object.values(DISEASE_DATABASE).filter(d => d.type !== 'None')
  
  // Dedup by name to keep the list clean (since we have tomato_early_blight, potato_late_blight overrides etc.)
  const uniqueNames = new Set()
  const displayDiseases = []
  for (let d of diseases) {
    if (!uniqueNames.has(d.name)) {
      uniqueNames.add(d.name)
      displayDiseases.push(d)
    }
  }

  const [selected, setSelected] = useState(displayDiseases[0])

  const speakText = (text) => {
    if (!text || !window.speechSynthesis) return;
    const langCodeMap = {
      en: 'en-US', hi: 'hi-IN', mr: 'mr-IN',
      bn: 'bn-IN', ur: 'ur-PK', gu: 'gu-IN',
      pa: 'pa-IN', ta: 'ta-IN', te: 'te-IN',
      kn: 'kn-IN', ml: 'ml-IN'
    };
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = langCodeMap[i18n.language] || 'en-US';
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(utterance);
  };

  return (
    <div className="glass-card advisory-panel" style={{ marginTop: 24, padding: 32, borderColor: 'rgba(59, 130, 246, 0.2)' }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 16, marginBottom: 24, flexWrap: 'wrap' }}>
        <div style={{ background: 'rgba(59, 130, 246, 0.1)', padding: 12, borderRadius: 12 }}>
          <FiActivity size={24} style={{ color: 'var(--blue-400)' }} />
        </div>
        <div style={{ flex: 1 }}>
          <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '1.2rem', fontWeight: 700 }}>{t('features.smartAdvisory', 'AI Treatment Advisory')}</h3>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginTop: 4 }}>{t('features.smartAdvisoryDesc', 'Plain-language, step-by-step recommendations generated by our localized crop pathology logic.')}</p>
        </div>
      </div>

      <div className="adv-grid">
        <div className="adv-sidebar">
          <p style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-muted)', marginBottom: 12 }}>SELECT DISEASE</p>
          <div className="adv-list">
            {displayDiseases.map(d => (
              <button 
                key={d.name} 
                className={`adv-btn ${selected.name === d.name ? 'active' : ''}`}
                onClick={() => setSelected(d)}
                style={selected.name === d.name ? { borderLeftColor: d.color, background: 'var(--bg-tertiary)' } : {}}
              >
                <span className="adv-btn-icon">{d.icon}</span>
                <span className="adv-btn-text">{d.name}</span>
                {selected.name === d.name && <FiChevronRight size={14} style={{ color: d.color }} />}
              </button>
            ))}
          </div>
        </div>

        <div className="adv-content">
          <AnimatePresence mode="wait">
            <motion.div 
              key={selected.name}
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.3 }}
            >
              <div style={{ marginBottom: 24, paddingBottom: 16, borderBottom: '1px solid var(--border-color)' }}>
                <div style={{ display: 'flex', gap: 12, alignItems: 'center', marginBottom: 8 }}>
                  <span style={{ fontSize: '2rem' }}>{selected.icon}</span>
                  <div>
                    <h4 style={{ fontSize: '1.2rem', fontWeight: 700, fontFamily: 'var(--font-display)', color: selected.color }}>
                      {selected.name} Advisory
                    </h4>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                      <span className="tag tag-cyan">{selected.type}</span>
                      <span>Affects: {selected.crop}</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="adv-steps-grid">
                <div className="adv-step-card">
                  <div className="adv-step-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', color: 'var(--cyan-400)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <FiCheckCircle size={16} />
                      <span>{t('treatment_steps', 'Treatment Steps')}</span>
                    </div>
                    <button onClick={() => speakText(selected.treatment.join('. '))} className="btn btn-outline" style={{ padding: '4px 8px', fontSize: '0.75rem', borderColor: 'var(--cyan-400)', color: 'var(--cyan-400)' }}>
                      🔊 {t('read_advisory', 'Read')}
                    </button>
                  </div>
                  <ul className="adv-step-list">
                    {selected.treatment.map((t, idx) => (
                      <li key={idx}><span>{idx + 1}.</span> {t}</li>
                    ))}
                  </ul>
                </div>

                <div className="adv-step-card">
                  <div className="adv-step-header" style={{ color: 'var(--green-400)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <FiShield size={16} />
                      <span>{t('prevention_steps', 'Prevention Steps')}</span>
                    </div>
                  </div>
                  <ul className="adv-step-list">
                    {selected.prevention.map((t, idx) => (
                      <li key={idx}><span>•</span> {t}</li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="adv-timeline">
                <div className="adv-timeline-header">
                  <FiClock size={16} /> Suggested Action Timeline
                </div>
                <div style={{ padding: 16 }}>
                  <div className="timeline-row">
                    <div className="timeline-dot" style={{ background: 'var(--red-400)' }} />
                    <div className="timeline-content">
                      <strong>Immediate ({selected.urgency})</strong>
                      <p>Isolate affected plants. Do not compost infected leaves.</p>
                    </div>
                  </div>
                  <div className="timeline-row">
                    <div className="timeline-dot" style={{ background: 'var(--amber-400)' }} />
                    <div className="timeline-content">
                      <strong>Week 1</strong>
                      <p>Complete first cycle of recommended fungicide / treatment application.</p>
                    </div>
                  </div>
                  <div className="timeline-row" style={{ borderLeftColor: 'transparent' }}>
                    <div className="timeline-dot" style={{ background: 'var(--green-400)' }} />
                    <div className="timeline-content">
                      <strong>Week 2+</strong>
                      <p>Monitor daily for new spots. Apply preventative measures to healthy crops.</p>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>
      </div>

      <style>{`
        .adv-grid { display: grid; grid-template-columns: 240px 1fr; gap: 32px; }
        .adv-sidebar { border-right: 1px solid var(--border-color); padding-right: 16px; }
        .adv-list { display: flex; flex-direction: column; gap: 4px; max-height: 500px; overflow-y: auto; padding-right: 8px; }
        .adv-list::-webkit-scrollbar { width: 4px; }
        .adv-list::-webkit-scrollbar-thumb { background: var(--bg-tertiary); border-radius: 2px; }
        .adv-btn { display: flex; alignItems: center; gap: 10px; width: 100%; text-align: left; background: none; border: none; padding: 10px 12px; border-radius: var(--radius-sm); border-left: 3px solid transparent; color: var(--text-secondary); cursor: pointer; transition: all 0.2s; }
        .adv-btn:hover { background: var(--bg-tertiary); color: var(--text-primary); }
        .adv-btn-icon { font-size: 1.1rem; }
        .adv-btn-text { font-size: 0.85rem; font-weight: 600; flex: 1; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
        .adv-steps-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 24px; }
        .adv-step-card { background: var(--bg-tertiary); border-radius: var(--radius-md); border: 1px solid var(--border-color); }
        .adv-step-header { padding: 12px 16px; border-bottom: 1px solid var(--border-color); display: flex; align-items: center; gap: 8px; font-weight: 700; font-size: 0.9rem; background: rgba(0,0,0,0.1); border-radius: var(--radius-md) var(--radius-md) 0 0; }
        .adv-step-list { list-style: none; padding: 16px; display: flex; flex-direction: column; gap: 10px; margin: 0; }
        .adv-step-list li { display: flex; align-items: flex-start; gap: 8px; font-size: 0.85rem; color: var(--text-secondary); line-height: 1.5; }
        .adv-step-list li span { font-weight: 700; color: var(--text-muted); }
        .adv-timeline { background: var(--bg-tertiary); border-radius: var(--radius-md); border: 1px solid var(--border-color); }
        .adv-timeline-header { padding: 12px 16px; border-bottom: 1px solid var(--border-color); display: flex; align-items: center; gap: 8px; font-weight: 700; font-size: 0.9rem; background: rgba(0,0,0,0.1); border-radius: var(--radius-md) var(--radius-md) 0 0; color: var(--text-primary); }
        .timeline-row { display: flex; gap: 20px; padding-bottom: 20px; border-left: 2px solid var(--border-color); margin-left: 8px; position: relative; }
        .timeline-row:last-child { padding-bottom: 0; border-left-color: transparent; }
        .timeline-dot { width: 12px; height: 12px; border-radius: 50%; position: absolute; left: -7px; top: 0; border: 2px solid var(--bg-card); }
        .timeline-content { margin-top: -4px; }
        .timeline-content strong { display: block; font-size: 0.85rem; margin-bottom: 4px; color: var(--text-primary); }
        .timeline-content p { font-size: 0.8rem; color: var(--text-secondary); line-height: 1.5; margin: 0; }
        @media(max-width: 800px) {
          .adv-grid { grid-template-columns: 1fr; }
          .adv-sidebar { border-right: none; border-bottom: 1px solid var(--border-color); padding-right: 0; padding-bottom: 16px; }
          .adv-list { max-height: 200px; }
          .adv-steps-grid { grid-template-columns: 1fr; }
        }
      `}</style>
    </div>
  )
}
